language: cpp
sudo: false
matrix:
  include:
  - os: osx
    osx_image: xcode9.3
  - os: osx
    osx_image: xcode8.3
  - os: osx
    osx_image: xcode7.3
before_install:
- brew tap heavywatal/tap
script:
- uname -a; sw_vers; $CXX --version
- brew audit --strict cxxwtl sfmt-class
- brew install cxxwtl sfmt-class
- brew test cxxwtl sfmt-class
notifications:
  email: false
