language: cpp
sudo: false
matrix:
  include:
  - os: osx
    osx_image: xcode9.3
  - os: osx
    osx_image: xcode8.3
before_install:
- uname -a; sw_vers
- export HOMEBREW_NO_AUTO_UPDATE=1
- BREW_REPO_TAP=$(brew --repo $TRAVIS_REPO_SLUG)
- echo $BREW_REPO_TAP
- mkdir -p $BREW_REPO_TAP
- cp -a . $BREW_REPO_TAP
script:
- brew audit --strict Formula/*.rb
- brew install tumopp blackthunnus
- brew test sfmt-class cxxwtl tumopp blackthunnus
notifications:
  email: false
